name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.4
      with:
        PROJECT_FILE_PATH: src\Swashbuckle.AspNetCore.EsquioResolver
        PACKAGE_NAME: 'Swashbuckle.AspNetCore.EsquioResolver'
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      
       
    
